name: Cache vcpkg Dependencies

on:
  workflow_dispatch:

jobs:
  cache-vcpkg:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh

      - name: Install vcpkg dependencies
        run: ./vcpkg/vcpkg install --triplet x64-linux-release

      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: |
            vcpkg_installed
            ~/.cache/vcpkg
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
